### ISSUE TITLE
TVDeamon can't be build on newer OS

### ISSUE THREAD

**Issue by Saentist** [neolynx/tvdaemon#12]
I try to build on Debian 8 x64, Ubuntu 16.04 x86, Ubuntu 14.04 x64

> ./build.sh
++ cd /opt/build/tvdaemon
++ git submodule update --init --recursive
Submodule path 'tsdecrypt': checked out 'ddd76ac4394886d96278b9dd2f901e35edfc5f16'
lib/libdvbv5/Makefile.am: needs merge
error: you need to resolve your current index first
Unable to checkout 'b4dc25b03cad32cf61c7ef6b0d23d767ebcb834a' in submodule path 'v4l-utils'
++ die 'submodule update failed'
++ echo submodule update failed
submodule update failed
++ exit -1

**Comment by neolynx** [comment]
Hello,

tvdaemon should now build on Ubuntu >= trusty and Debian >= jessie

Also the README is updated with a small usage guide.


Thanks for reporting!

**Comment by Saentist** [comment]
Readme is not complite 

> libccrtp-dev
libjson-c-dev
libudev-dev
libconfig++8-dev

This also is needed  but still not luck to build 
>Making all in src
make[1]: Entering directory '/opt/tvdaemon/src'
  CXX      tvdaemon-tvdaemon.o
  CXXLD    tvdaemon
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_pmt_store'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_pmt_stream_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_pat_program_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_sdt_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_sdt_service_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_pat_store'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_pmt_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_pat_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_mpeg_ts_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_desc_create'
../lib/.libs/libtvdaemon.so: undefined reference to `dvb_table_sdt_store'
collect2: error: ld returned 1 exit status
Makefile:410: recipe for target 'tvdaemon' failed
make[1]: *** [tvdaemon] Error 1
make[1]: Leaving directory '/opt/tvdaemon/src'
Makefile:523: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
++ die 'make tvdaemon failed'
++ echo make tvdaemon failed
make tvdaemon failed
++ exit -1

**Comment by neolynx** [comment]
did you try a fresh checkout? I tested on debian jessie and I did not get that error. what distro are you building with?
the problem might be the git submodules and the build.sh is not handling them correctly. I will try to fix that. 
I will update the Readme, thanks!

**Comment by Saentist** [comment]
Yes I did Fresh "git clone"
but on  Debian 8 x64 

> #uname -a
Linux FlamingoXL 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.8 (jessie)
Release:        8.8
Codename:       jessie


and  Ubuntu 16.04 x86, 

> #uname -a
Linux saen-ET1610PT 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:28:22 UTC 2017 i686 i686 i686 GNU/Linux
#lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

crash with same messages.
I can provide full build log from both, if this will help.

**Comment by timofurrer** [comment]
Using an up-to-date Ubuntu works absolutely fine with a new clone and by following the steps in `README`.

```bash
$ uname -a
Linux krypton 4.10.0-22-generic #24-Ubuntu SMP 
Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

Not sure why your linker fails though ...

**Comment by Saentist** [comment]
log of ubuntu
[ubuntu.txt](https://github.com/neolynx/tvdaemon/files/1066346/ubuntu.txt)
log of debian
[debian.txt](https://github.com/neolynx/tvdaemon/files/1066351/debian.txt)

Under Ubuntu 14.04 is OK, but I don't have tuners to test on it.
